set -g mode-keys vi
#set -g window-status-format "#I.#W"
#set -g window-status-current-format "#[reverse] #I.#W #[noreverse]"

set -s escape-time 10
#set -g mode-style bg=#8aadf4,fg=#494d64,reverse
#set -g message-style bg=#8aadf4,fg=#494d64
#set -g message-command-style bg=#8aadf4,fg=#494d64,reverse
#set -g status-style bg=#363a4f,fg=#8aadf4
#set -g pane-active-border-style fg=#eed49f

#set -g status-left " #{=-15:session_name} | "
#set -g status-left-length 19
#set -g status-right "#{E:user} "

set -g prefix C-f
set -g prefix2 C-b

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind y display-popup -x C -y C -h 90% -w 90% -E -d '#{pane_current_path}' 'tmux new-session yazi \; set status off'
bind g display-popup -x C -y C -h 90% -w 90% -E -d '#{pane_current_path}' 'tmux new-session lazygit \; set status off'
bind e capture-pane -J -S - \; \
  save-buffer /tmp/tmux-buffer.txt \; \
  display-popup -x C -y C -h 90% -w 90% -E "$EDITOR + /tmp/tmux-buffer.txt"

# Options to make tmux more pleasant
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# for shift-space
set -s extended-keys on

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
# basic, slanted, rounded, custom
set -g @catppuccin_window_status_style "basic"

set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

set -g @catppuccin_status_connect_separator "yes"
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator ""
#set -g @catppuccin_status_left_separator ""
#set -g @catppuccin_status_right_separator ""

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# For TPM, instead use `run ~/.tmux/plugins/tmux/catppuccin.tmux`

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ga status-right "#{E:@catppuccin_status_session}"

set -ga message-command-style reverse

